esphome:
  name: $internal_name
  platform: ESP8266
  board: esp01_1m

<<: !include base.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "${name} button"
    on_press:
      - switch.toggle: relay

sensor:
  #- platform: wifi_signal
  #  name: "${name} WiFi Signal"
  #  update_interval: 60s
  #- platform: uptime
  #  name: "${name} Uptime"
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO04
    cf1_pin: GPIO05
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}
    current:
      name: "${name} Amperage"
      unit_of_measurement: A
    voltage:
      name: "${name} Voltage"
      unit_of_measurement: V
    power:
      name: "${name} Wattage"
      unit_of_measurement: W
      id: power
    change_mode_every: 8
    update_interval: 10s
  - platform: total_daily_energy
    name: "${name} Total Daily Energy"
    power_id: power
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
    unit_of_measurement: kWh

status_led:
  pin: GPIO13
